# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OtterV3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OtterV3

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'GoogleSignIn'
  pod 'SnapKit', '~> 5.0.0'
  pod 'paper-onboarding'
  pod 'lottie-ios'
  pod 'TextFieldEffects'
  pod 'SwiftLint'

  target 'OtterV3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
